### ISSUE TITLE
Why cnetplot work with some pathways but not for others?

### ISSUE THREAD

**Issue by Chrisdoan9** [GuangchuangYu/doseplot#4]
Hi Dr. Yu,

This tool is very nice and I try to make cnetplot for some pathways of interested. However, I got this error:
results is out put from limma
```
gene_list <- results$logFC
names(gene_list) <- rownames(results_2)
gene <- names(gene_list)[abs(gene_list) > 0.00001]
gene <- bitr(gene, fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)$ENTREZID
m_t2g <- msigdbr(species = "Homo sapiens", category = "C2") %>% 
  dplyr::select(gs_name, entrez_gene)
gene_entrez <- bitr(names(gene_list), fromType = "SYMBOL", toType = "ENTREZID", OrgDb = org.Hs.eg.db)
gene_entrez$foldChange <- gene_list[gene_entrez$SYMBOL]
fold_changes <- setNames(gene_entrez$foldChange, gene_entrez$ENTREZID)
x <- enricher(gene, TERM2GENE = m_t2g)
cnetplot(x, showCategory = c("COULOUARN_TEMPORAL_TGFB1_SIGNATURE_UP", "BIOCARTA_IL12_PATHWAY"), foldChange=fold_changes) 
Error in graph.data.frame(x, directed = FALSE) : 
  the data frame should contain at least two columns
```
I changed with others pathways in x@result and it worked, so I don't know why.
Could we combine pathways from condition 2 vs condition 1 with pathways from condition 3 vs condition 1 into one plot using 2 colors or we have to make 2 separate plots? I really appreciate it!

**Comment by GuangchuangYu** [comment]
pls go to <https://github.com/YuLab-SMU/enrichplot/issues> for feature request. The `doseplot` will not be updated.
